### ISSUE TITLE
Generate sitemap.xml for the accessibility site

### ISSUE THREAD

**Issue by dmundra** [CivicActions/accessibility#65] opened 2021-02-04 18:07 UTC
@lukefretwell, I found this plugin https://github.com/jekyll/jekyll-sitemap to generate a sitemap for Jekyll but there might be a different way to do that.

Cc: @jerseycheese

**Comment by lukefretwell** [comment] 2021-02-06 04:17
@dmundra can you verify I did this successfully and close the issue if yes?

**Comment by dmundra** [comment] 2021-02-08 15:05
@lukefretwell, looking good https://civicactions.github.io/accessibility/sitemap.xml. Thank you!

**Comment by dmundra** [comment] 2021-02-08 15:07
Whoops, spoke too soon. It looks like there is an extra /accessibility/ in the path. E.g.s

* https://civicactions.github.io/accessibility/accessibility/handbook/tools
* https://civicactions.github.io/accessibility/accessibility/people/luke-fretwell

**Comment by dmundra** [comment] 2021-02-08 15:11
@lukefretwell changing the URL on this line https://github.com/CivicActions/accessibility/blob/105b93d951bf13d6ff5ca4e10c0c56e80fa0592e/_config.yml#L12 to 'https://civicactions.github.io' probably will do it.

**Comment by lukefretwell** [comment] 2021-02-09 00:54
@dmundra my fear is that will break the website on GitHub Pages. I'll try this when I push the new code shortly and will revert if it breaks.

@brianseek @grugnog thoughts on what the issue is here?

**Comment by dmundra** [comment] 2021-02-09 15:45
@lukefretwell looks like the change didn't work as I saw you revert it?

**Comment by brianseek** [comment] 2021-02-09 16:22
> @dmundra my fear is that will break the website on GitHub Pages. I'll try this when I push the new code shortly and will revert if it breaks.
> 
> @brianseek @grugnog thoughts on what the issue is here?

@lukefretwell I thought that this may be related to similar baseurl issues that you were having in the past, but I don't think it is. I think the next step would be to crack open the sitemap script and see how it is putting the URLs together to see where the double /accessibility/ is. A simple alternative would be to just create the sitemap manually for now.

**Comment by dmundra** [comment] 2021-02-09 19:17
Looking good https://civicactions.github.io/accessibility/sitemap.xml and I think this can be closed now.

**Closed** 2021-02-09 20:13 UTC
Labels: website
